crm_system/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls")),
    path("ads/", include("advertising.urls")),
    path("leads/", include("leads.urls")),
    path("contracts/", include("contracts.urls")),
    path("customers/", include("customers.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_system/crm_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls"))
]

crm_system/customers/urls.py
from django.urls import path
from .views import CustomersList, CustomerDetail, CustomerCreate, CustomerUpdate, CustomerDelete

app_name = "customers"


urlpatterns = [
    path("", CustomersList.as_view(), name="customers-list"),
    path("detail/<int:pk>/", CustomerDetail.as_view(), name="customer-detail"),
    path("create/", CustomerCreate.as_view(), name="customer-create"),
    path("update/<int:pk>/", CustomerUpdate.as_view(), name="customer-update"),
    path("delete/<int:pk>/", CustomerDelete.as_view(), name="customer-delete")
]

crm_system/leads/urls.py
from django.urls import path
from .views import LeadsList, LeadsDetail, LeadsCreate, LeadsUpdate, LeadsDelete


app_name = "leads"


urlpatterns = [
    path("", LeadsList.as_view(), name="leads-list"),
    path("detail/<int:pk>/", LeadsDetail.as_view(), name="lead-detail"),
    path("create/", LeadsCreate.as_view(), name="leads-create"),
    path("update/<int:pk>/", LeadsUpdate.as_view(), name="lead-update"),
    path("delete/<int:pk>/", LeadsDelete.as_view(), name="lead-delete"),
]

crm_system/customers/models.py
from django.db import models
from django.urls import reverse_lazy
from leads.models import Leads
from contracts.models import Contract


class ActiveLead(models.Model):
    """Активные клиенты"""
    class Meta:
        verbose_name = "Активный клиент"
        verbose_name_plural = "Активные клиенты"

    lead = models.ForeignKey(to=Leads, on_delete=models.CASCADE, verbose_name="Клиент", related_name="active_lead")
    contract = models.ForeignKey(to=Contract, on_delete=models.CASCADE, verbose_name="Контракт", related_name="active_lead")

    def get_absolute_url(self):
        return reverse_lazy("customers:customer-detail", kwargs={"pk": self.pk})

crm_system/customers/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic
from .models import ActiveLead


class CustomersList(UserPassesTestMixin, generic.ListView):
    """Просмотр активных клиентов"""
    model = ActiveLead
    template_name = "customers/customers-list.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        customers = ActiveLead.objects.select_related("lead", "contract").all()
        data["customers"] = customers
        return data

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists()


class CustomerDetail(UserPassesTestMixin, generic.DetailView):
    """Детальный просмотр активного клиента"""
    model = ActiveLead
    template_name = "customers/customers-detail.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        customer = ActiveLead.objects.select_related("lead", "contract").get(pk=self.object.pk)
        data["customer"] = customer
        return data

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists()


class CustomerCreate(generic.CreateView):
    """Создание активного клиента"""
    model = ActiveLead
    fields = "__all__"
    context_object_name = "customer"
    template_name = "customers/customers-create.html"

    def get_success_url(self):
        return self.object.get_absolute_url()


class CustomerUpdate(generic.UpdateView):
    """Изменение активного клиента"""
    model = ActiveLead
    fields = "__all__"
    context_object_name = "customer"
    template_name = "customers/customers-edit.html"

    def get_success_url(self):
        return self.object.get_absolute_url()

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists()


class CustomerDelete(generic.DeleteView):
    """Удаление активного клиента"""
    model = ActiveLead
    template_name = "customers/customers-delete.html"
    context_object_name = "customer"
    success_url = reverse_lazy("customers:customers-list")

crm_system/templates/customers/customers-create.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание активного клиента</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="{% url 'customers:customer-create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/customers/customers-delete.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление активного клиента</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ customer.lead.first_name }} {% if customer.lead.last_name %}{{ customer.lead.last_name }} {% endif %}"?</p>
        <form method="POST" action="{% url 'customers:customer-delete' customer.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/customers/customers-detail.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация об активном клиенте</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ customer.lead.first_name }} {% if customer.lead.last_name %}{{ customer.lead.last_name }} {% endif %}</h5>
                <p class="card-text">{{ customer.lead.phone }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ customer.lead.email }}</div>
                <div class="d-flex justify-content-end fw-bold">Контракт: {{ customer.contract.name }}</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="{% url 'customers:customer-update' customer.pk %}" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/customers/customers-edit.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование активного клиента</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="{% url 'customers:customer-update' customer.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/customers/customers-list.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Активные клиенты</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="{% url 'customers:customer-create' %}" class="btn btn-success p-2">Создать</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for customer in customers %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{{customer.get_absolute_url}}" class="text-decoration-none link-dark">{{ customer.lead.first_name }} {% if customer.lead.last_name %}{{ customer.lead.last_name }} {% endif %}</a>
                <a href="{% url 'customers:customer-delete' customer.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}