crm_system/advertising/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreate, AdsUpdate, AdsDelete, Statistic

app_name = "advertising"


urlpatterns = [
    path("", AdsList.as_view(), name="ads-list"),
    path("detail/<int:pk>/", AdsDetail.as_view(), name="ads-detail"),
    path("create/", AdsCreate.as_view(), name="ads-create"),
    path("update/<int:pk>/", AdsUpdate.as_view(), name="ads-update"),
    path("delete/<int:pk>", AdsDelete.as_view(), name="ads-delete"),
    path("statistic/", Statistic.as_view(), name="statistic")
]

crm_system/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls")),
    path("ads/", include("advertising.urls")),
    path("leads/", include("leads.urls")),
    path("contracts/", include("contracts.urls")),
    path("customers/", include("customers.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_system/crm_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls"))
]

crm_system/customers/urls.py
from django.urls import path
from .views import CustomersList, CustomerDetail, CustomerCreate, CustomerUpdate, CustomerDelete

app_name = "customers"


urlpatterns = [
    path("", CustomersList.as_view(), name="customers-list"),
    path("detail/<int:pk>/", CustomerDetail.as_view(), name="customer-detail"),
    path("create/", CustomerCreate.as_view(), name="customer-create"),
    path("update/<int:pk>/", CustomerUpdate.as_view(), name="customer-update"),
    path("delete/<int:pk>/", CustomerDelete.as_view(), name="customer-delete")
]

crm_system/leads/urls.py
from django.urls import path
from .views import LeadsList, LeadsDetail, LeadsCreate, LeadsUpdate, LeadsDelete


app_name = "leads"


urlpatterns = [
    path("", LeadsList.as_view(), name="leads-list"),
    path("detail/<int:pk>/", LeadsDetail.as_view(), name="lead-detail"),
    path("create/", LeadsCreate.as_view(), name="leads-create"),
    path("update/<int:pk>/", LeadsUpdate.as_view(), name="lead-update"),
    path("delete/<int:pk>/", LeadsDelete.as_view(), name="lead-delete"),
]

crm_system/products/urls.py
from django.urls import path
from .views import ProductsList, ProductDetail, ProductCreate, ProductUpdate, ProductDelete


app_name = "products"


urlpatterns = [
    path("", ProductsList.as_view(), name="products"),
    path("detail/<int:pk>/", ProductDetail.as_view(), name="product-detail"),
    path("update/<int:pk>/", ProductUpdate.as_view(), name="product-update"),
    path("create/", ProductCreate.as_view(), name="product-create"),
    path("delete/<int:pk>/", ProductDelete.as_view(), name="product-delete")
]

crm_system/leads/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse_lazy
from advertising.models import AdvertisingCompany


class Leads(models.Model):
    """Потенциальный клиент"""
    regex_phone = RegexValidator(
        regex=r"^((8|\+7|)(\d{10}))$", message="Формат номера телефона должен быть: +79999999999 или 89999999999"
    )

    class Meta:
        verbose_name = "Потенциальный клиент"
        verbose_name_plural = "Потенциальные клиенты"

    first_name = models.CharField(max_length=20, verbose_name="Фамилия и имя")
    last_name = models.CharField(max_length=50, verbose_name="Отчество (при наличии)", blank=True, null=True)
    phone = models.CharField(max_length=12, validators=[regex_phone], verbose_name="Номер телефона", unique=True)
    email = models.EmailField(verbose_name="Электронная почта", unique=True)
    advertising = models.ForeignKey(AdvertisingCompany, on_delete=models.CASCADE, related_name="leads", verbose_name="Рекламная компания")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse_lazy("leads:lead-detail", kwargs={"pk": self.pk})

crm_system/templates/users/index.html
{% extends "_base.html" %}

{% block content %}
    {% if user.is_authenticated %}
        <h2 class="fw-bold">Общая статистика</h2>
        <div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
            {% if perms.products.view_product %}
                <div class="col">
                    <div class="card border-light shadow" style="background: #eee">
                        <div class="card-body bg-gray-900">
                            <h5 class="card-title fw-bold">
                                <a href="{% url 'products:products' %}" class="link-dark text-decoration-none">Услуг</a>
                            </h5>
                            <i class="fas fa-microchip float-end"></i>
                            <p class="card-text fw-bold fs-1">{{ products_count }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if perms.advertising.view_advertisingcompany %}
                <div class="col">
                    <div class="card border-light shadow" style="background: #eee">
                        <div class="card-body">
                            <h5 class="card-title fw-bold">
                                <a href="{% url 'advertising:ads-list' %}" class="link-dark text-decoration-none">Рекламных компаний</a>
                            </h5>
                            <i class="fas fa-ad float-end"></i>
                            <p class="card-text fw-bold fs-1">{{ advertisements_count }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if perms.leads.view_leads %}
                <div class="col">
                    <div class="card border-light shadow" style="background: #eee">
                        <div class="card-body">
                            <h5 class="card-title fw-bold">
                                <a href="{% url 'leads:leads-list' %}" class="link-dark text-decoration-none">Лидов</a>
                            </h5>
                            <i class="fas fa-user-clock float-end"></i>
                            <p class="card-text fw-bold fs-1">{{ leads_count }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if perms.customers.view_customer %}
                <div class="col">
                    <div class="card border-light shadow">
                        <div class="card-body" style="background: #eee">
                            <h5 class="card-title fw-bold">
                                <a href="{% url 'customers:customers-list' %}" class="link-dark text-decoration-none">Активных клиентов</a>
                            </h5>
                            <i class="fas fa-user-check float-end"></i>
                            <p class="card-text fw-bold fs-1">{{ customers_count }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    {% else %}
        <p>Вы не авторизованы!</p>
    {% endif %}
{% endblock %}