crm_system/advertising/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreate, AdsUpdate, AdsDelete, Statistic

app_name = "advertising"


urlpatterns = [
    path("", AdsList.as_view(), name="ads-list"),
    path("detail/<int:pk>/", AdsDetail.as_view(), name="ads-detail"),
    path("create/", AdsCreate.as_view(), name="ads-create"),
    path("update/<int:pk>/", AdsUpdate.as_view(), name="ads-update"),
    path("delete/<int:pk>", AdsDelete.as_view(), name="ads-delete"),
    path("statistic/", Statistic.as_view(), name="statistic")
]

crm_system/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls")),
    path("ads/", include("advertising.urls")),
    path("leads/", include("leads.urls")),
    path("contracts/", include("contracts.urls")),
    path("customers/", include("customers.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_system/contracts/urls.py
from django.urls import path
from .views import ContractList, ContractDetail, ContractCreate, ContractUpdate, ContractDelete

app_name = "contracts"


urlpatterns = [
    path("", ContractList.as_view(), name="contracts-list"),
    path("detail/<int:pk>/", ContractDetail.as_view(), name="contract-detail"),
    path("create/", ContractCreate.as_view(), name="contract-create"),
    path("update/<int:pk>/", ContractUpdate.as_view(), name="contract-update"),
    path("delete/<int:pk>/", ContractDelete.as_view(), name="contract-delete")
]

crm_system/crm_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls"))
]

crm_system/customers/urls.py
from django.urls import path
from .views import CustomersList, CustomerDetail, CustomerCreate, CustomerUpdate, CustomerDelete

app_name = "customers"


urlpatterns = [
    path("", CustomersList.as_view(), name="customers-list"),
    path("detail/<int:pk>/", CustomerDetail.as_view(), name="customer-detail"),
    path("create/", CustomerCreate.as_view(), name="customer-create"),
    path("update/<int:pk>/", CustomerUpdate.as_view(), name="customer-update"),
    path("delete/<int:pk>/", CustomerDelete.as_view(), name="customer-delete")
]

crm_system/leads/urls.py
from django.urls import path
from .views import LeadsList, LeadsDetail, LeadsCreate, LeadsUpdate, LeadsDelete


app_name = "leads"


urlpatterns = [
    path("", LeadsList.as_view(), name="leads-list"),
    path("detail/<int:pk>/", LeadsDetail.as_view(), name="lead-detail"),
    path("create/", LeadsCreate.as_view(), name="leads-create"),
    path("update/<int:pk>/", LeadsUpdate.as_view(), name="lead-update"),
    path("delete/<int:pk>/", LeadsDelete.as_view(), name="lead-delete"),
]

crm_system/products/urls.py
from django.urls import path
from .views import ProductsList, ProductDetail, ProductCreate, ProductUpdate, ProductDelete


app_name = "products"


urlpatterns = [
    path("", ProductsList.as_view(), name="products"),
    path("detail/<int:pk>/", ProductDetail.as_view(), name="product-detail"),
    path("update/<int:pk>/", ProductUpdate.as_view(), name="product-update"),
    path("create/", ProductCreate.as_view(), name="product-create"),
    path("delete/<int:pk>/", ProductDelete.as_view(), name="product-delete")
]

crm_system/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>
        {% block title %}
            CRM
        {% endblock %}
    </title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.products.view_product %}
            <li><a href="{% url 'products:products' %} " class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.advertising.view_advertisingcompany %}
            <li><a href="{% url 'advertising:ads-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.leads.view_leads %}
            <li><a href="{% url 'leads:leads-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contracts.view_contract %}
            <li><a href="{% url 'contracts:contracts-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.customers.view_customer %}
            <li><a href="{% url 'customers:customers-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <form id="logout-form" action="{% url "registration:logout" %}" method="POST">
                      {% csrf_token %}
                      <button class="bar-item text-decoration-none px-3 py-3 d-block" type="submit">
                          <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
                      </button>
                    </form>
                </li>
            {% else %}
                <li>
                    <a href="{% url "registration:login" %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                        <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Войти</span>
                    </a>
                </li>
                 <li>
                    <a href="{% url "registration:register" %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                        <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Регистрация</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>