crm_system/advertising/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreate, AdsUpdate, AdsDelete, Statistic

app_name = "advertising"


urlpatterns = [
    path("", AdsList.as_view(), name="ads-list"),
    path("detail/<int:pk>/", AdsDetail.as_view(), name="ads-detail"),
    path("create/", AdsCreate.as_view(), name="ads-create"),
    path("update/<int:pk>/", AdsUpdate.as_view(), name="ads-update"),
    path("delete/<int:pk>", AdsDelete.as_view(), name="ads-delete"),
    path("statistic/", Statistic.as_view(), name="statistic")
]

crm_system/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls")),
    path("ads/", include("advertising.urls")),
    path("leads/", include("leads.urls")),
    path("contracts/", include("contracts.urls")),
    path("customers/", include("customers.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_system/crm_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("registration.urls")),
    path("products/", include("products.urls"))
]

crm_system/leads/urls.py
from django.urls import path
from .views import LeadsList, LeadsDetail, LeadsCreate, LeadsUpdate, LeadsDelete


app_name = "leads"


urlpatterns = [
    path("", LeadsList.as_view(), name="leads-list"),
    path("detail/<int:pk>/", LeadsDetail.as_view(), name="lead-detail"),
    path("create/", LeadsCreate.as_view(), name="leads-create"),
    path("update/<int:pk>/", LeadsUpdate.as_view(), name="lead-update"),
    path("delete/<int:pk>/", LeadsDelete.as_view(), name="lead-delete"),
]

crm_system/templates/ads/ads-create.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="{% url "advertising:ads-create" %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/ads/ads-delete.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.name }}"?</p>
        <form method="POST" action="{% url "advertising:ads-delete" ads.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/ads/ads-detail.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ ads.name }}</h5>
                <p class="card-text">{{ ads.product.name }}</p>
                <p class="card-text">{{ ads.channel }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ ads.budget }}руб</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="{% url "advertising:ads-update" ads.pk %}" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/ads/ads-edit.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="{% url "advertising:ads-update" ads.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm_system/templates/ads/ads-list.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Рекламные компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="{% url "advertising:ads-create" %}" class="btn btn-success p-2">Создать</a>
        <a href="{% url 'advertising:statistic' %}" class="btn btn-primary p-2">Статистика</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for ad in ads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{{ad.get_absolute_url}}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                <a href="{% url "advertising:ads-delete" ad.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

crm_system/templates/ads/ads-statistic.html
{% extends "_base.html" %}
{% load divide_filter %}

{% block content %}
<h2 class="fw-bold">Статистика рекламных компаний</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">
        <ul class="list-group">
            {% if ads %}
                {% for ad in ads %}
                <li class="list-group-item list-group-item-light d-flex justify-content-between">
                    <a href="/ads/{{ ad.pk }}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                    <p>Лидов: {{ ad.clients_count }} | Активных клиентов: {{ ad.active_clients_count }} | Соотношение контрактов к затратам: {% divide ad.total_income ad.total_expenses %} </p>
                </li>
                {% endfor %}
            {% else %}
                <p>Еще нет рекламных компаний</p>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}